import type { NextPage } from 'next';
import Head from 'next/head';
import React from 'react';
import { Button } from '../components/Button';

const Home: NextPage = () => {
  return (
    <div className="w-full flex flex-col items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4 justify-items-center">
        <Button.Primary>Filled</Button.Primary>
        <Button.Primary variant="bordered">Bordered</Button.Primary>
        <Button.Primary variant="soft">Soft</Button.Primary>
        <Button.Primary variant="text">Text</Button.Primary>
        <Button.Secondary>Filled</Button.Secondary>
        <Button.Secondary variant="bordered">Bordered</Button.Secondary>
        <Button.Secondary variant="soft">Soft</Button.Secondary>
        <Button.Secondary variant="text">Text</Button.Secondary>
        <Button.Success>Filled</Button.Success>
        <Button.Success variant="bordered">Bordered</Button.Success>
        <Button.Success variant="soft">Soft</Button.Success>
        <Button.Success variant="text">Text</Button.Success>
        <Button.Warning>Filled</Button.Warning>
        <Button.Warning variant="bordered">Bordered</Button.Warning>
        <Button.Warning variant="soft">Soft</Button.Warning>
        <Button.Warning variant="text">Text</Button.Warning>
        <Button.Danger>Filled</Button.Danger>
        <Button.Danger variant="bordered">Bordered</Button.Danger>
        <Button.Danger variant="soft">Soft</Button.Danger>
        <Button.Danger variant="text">Text</Button.Danger>
        <Button.Info>Filled</Button.Info>
        <Button.Info variant="bordered">Bordered</Button.Info>
        <Button.Info variant="soft">Soft</Button.Info>
        <Button.Info variant="text">Text</Button.Info>
      </div>
      <div className="mt-3 grid grid-cols-1 md:grid-cols-7 gap-4 justify-items-center">
        <Button.Info rounded="none">Rounded none</Button.Info>
        <Button.Info rounded="sm">Rounded sm</Button.Info>
        <Button.Info rounded="md">Rounded md</Button.Info>
        <Button.Info rounded="lg">Rounded lg</Button.Info>
        <Button.Info rounded="xl">Rounded xl</Button.Info>
        <Button.Info rounded="2xl">Rounded 2xl</Button.Info>
        <Button.Info rounded="full">Rounded full</Button.Info>
      </div>
      <div className="mt-3 grid grid-cols-1 md:grid-cols-5 gap-4 justify-items-center">
        <Button.Success shadow="sm">Shadow sm</Button.Success>
        <Button.Success shadow="md">Shadow md</Button.Success>
        <Button.Success shadow="lg">Shadow lg</Button.Success>
        <Button.Success shadow="xl">Shadow xl</Button.Success>
        <Button.Success shadow="2xl">Shadow 2xl</Button.Success>
      </div>
      <div className="mt-3 grid grid-cols-1 md:grid-cols-6 gap-4 justify-items-center">
        <Button.Warning height="xs">Height xs</Button.Warning>
        <Button.Warning height="sm">Height sm</Button.Warning>
        <Button.Warning height="md">Height md</Button.Warning>
        <Button.Warning height="lg">Height lg</Button.Warning>
        <Button.Warning height="xl">Height xl</Button.Warning>
        <Button.Warning height="2xl">Height 2xl</Button.Warning>
      </div>
      <div className="mt-3 grid grid-cols-1 md:grid-cols-7 gap-4 justify-items-center">
        <Button.Danger width="xs">Width xs</Button.Danger>
        <Button.Danger width="sm">Width sm</Button.Danger>
        <Button.Danger width="md">Width md</Button.Danger>
        <Button.Danger width="lg">Width lg</Button.Danger>
        <Button.Danger width="xl">Width xl</Button.Danger>
        <Button.Danger width="2xl">Width 2xl</Button.Danger>
        <Button.Danger width="full">Width 2xl</Button.Danger>
      </div>
    </div>
  );
};

export default Home;
