import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React from "react";

interface BoxProps {
  heading: string;
  content: string;
  link: string;
}

const Box: React.FC<BoxProps> = ({heading, content, link}) => {
  return (
    <a href={link} className="border hover:border-blue-600 hover:text-blue-600 p-5 rounded-xl w-72">
      <h2 className='text-2xl pb-3'>{heading} &rarr;</h2>
      <p className='text-xl'>{content}</p>
    </a>
  )
}

const Home: NextPage = () => {
  return (
    <div className="w-full h-screen flex flex-col justify-between items-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>

      <main className="flex flex-col justify-evenly items-center h-full">
        <h1 className="text-center text-6xl">
          Welcome to <a href="https://nextjs.org" className='text-blue-600 hover:underline'>Next.js!</a>
        </h1>

        <p className="text-2xl text-center">
          Get started by editing{' '}
          <code className="text-xl p-3 bg-gray-50 ">pages/index.tsx</code>
        </p>

        <div className="grid grid-rows-2 grid-cols-2 gap-8 justify-items-center">
          <Box heading={'Documentation'} content={'Find in-depth information about Next.js features and API.'}
               link={'https://nextjs.org/docs'}/>
          <Box heading={'Learn'} content={'Learn about Next.js in an interactive course with quizzes!'}
               link={'https://nextjs.org/learn'}/>
          <Box heading={'Examples'} content={'Discover and deploy boilerplate example Next.js projects.'}
               link={'https://github.com/vercel/next.js/tree/canary/examples'}/>
          <Box heading={'Deploy'} content={'Instantly deploy your Next.js site to a public URL with Vercel.'}
               link={'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'}/>
        </div>
      </main>

      <footer className="border-t w-full text-center p-5">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
